# --------------------------------------------------------------------------
#  Benchmark Configuration for MDS Algorithms
#
#  This file defines the models and their parameters to be compared by the
#  run_benchmark.py script.
# --------------------------------------------------------------------------

models_to_run:

  - name: "SGD-MDS (Iter Stopper)"
    class: "SGDMDS"
    params:
      stopper: "iterations"
      # max_iter will be supplied from the command line
      lr_init: 0.01
      scheduler: "constant"
      random_state: 42

  - name: "SGD-MDS (Threshold Stopper)"
    class: "SGDMDS"
    params:
      stopper: "threshold"
      stopper_params:
        threshold: 0.01
        patience: 3
      # max_iter will be supplied from the command line
      lr_init: 0.01
      scheduler: "convergence"
      scheduler_params:
        lr_final_phase1: 0.01
        phase1_iters: 100
      random_state: 42
      
  - name: "Scikit-learn MDS"
    class: "SklearnMDS"
    params:
      dissimilarity: "precomputed"
      n_init: 1
      # max_iter will be supplied from the command line
      random_state: 42
      n_jobs: -1